name: igrins_rv
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - matplotlib
  - numpy
  - pandas
  - scipy
  - astropy
  - multiprocess
  - cython
  - requests
  - nlopt=2.7.*
  - numba
  - pip
  - pip:
    - pysynphot
    - more_itertools
    - pqdm
